//! \file inst_dialog.h
//!
/***************************************************************************/
/* Tool Gear (www.llnl.gov/CASC/tool_gear)                                 */
/* Version 2.00                                             March 29, 2006 */
/* Please see COPYRIGHT AND LICENSE information at the end of this file.   */
/***************************************************************************/
// John May, 11 October 2002

#ifndef INST_DIALOG_H
#define INST_DIALOG_H

#include <qptrlist.h>
#include <qpair.h>
#include <qstringlist.h>
#include <qvaluelist.h>
#include "inst_dialog_base.h"
#include "tg_inst_spec.h"
#include "uimanager.h"

//! Dialog for requesting automatic instrumentation.

//! This is not an automatically generated class.  It uses the
//! base class that's generated by the Qt designer and extends
//! it to add the necessary functionality.
//! This dialog lets the user select instrumentaiton to install
//! at selected locations in the target program.
class InstrumentationDialog : public InstrumentationDialogBase {
	Q_OBJECT
public:
	//! Creates a dialog to ask for information from the user.
	//! Needs the uimanager to find out what actions are available.
	InstrumentationDialog( UIManager * um, QWidget * parent = 0,
			const char * name = 0, bool modal = FALSE,
			WFlags fl = 0 );
	~InstrumentationDialog();

	//! Return the list of instrumentation reqeusts.  Auto-deletion
	//! is set by default on this list, so the items it contains
	//! will be deleted when removed from the list, or when the
	//! list itself is destroyed.
	QPtrList<TGInstSpec> * instrumentationList();
protected slots:
	//! Called when the user wants to add an instrumentation
	//! specification to the list
	virtual void instrumentationDefined();

	//! Called when the user wants to remove selected items
	//! from the list being built in this dialog
	virtual void deleteRequested();

protected:
	QValueList<QPair<QString,QString> > actionList;
	QPtrList<TGInstSpec> * inst_requests;
	static const TG_InstPtLocation iploc[4];
	static const TG_InstPtType iptype[4];
};

#endif
/******************************************************************************
COPYRIGHT AND LICENSE

Copyright (c) 2006, The Regents of the University of California.
Produced at the Lawrence Livermore National Laboratory
Written by John Gyllenhaal (gyllen@llnl.gov), John May (johnmay@llnl.gov),
and Martin Schulz (schulz6@llnl.gov).
UCRL-CODE-220834.
All rights reserved.

This file is part of Tool Gear.  For details, see www.llnl.gov/CASC/tool_gear.

Redistribution and use in source and binary forms, with or
without modification, are permitted provided that the following
conditions are met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the disclaimer below.

* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the disclaimer (as noted below) in
  the documentation and/or other materials provided with the distribution.

* Neither the name of the UC/LLNL nor the names of its contributors may
  be used to endorse or promote products derived from this software without
  specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OF THE UNIVERSITY 
OF CALIFORNIA, THE U.S. DEPARTMENT OF ENERGY OR CONTRIBUTORS BE LIABLE 
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ADDITIONAL BSD NOTICE

1. This notice is required to be provided under our contract with the 
   U.S. Department of Energy (DOE). This work was produced at the 
   University of California, Lawrence Livermore National Laboratory 
   under Contract No. W-7405-ENG-48 with the DOE.

2. Neither the United States Government nor the University of California 
   nor any of their employees, makes any warranty, express or implied, 
   or assumes any liability or responsibility for the accuracy, completeness,
   or usefulness of any information, apparatus, product, or process disclosed,
   or represents that its use would not infringe privately-owned rights.

3. Also, reference herein to any specific commercial products, process,
   or services by trade name, trademark, manufacturer or otherwise does not
   necessarily constitute or imply its endorsement, recommendation, or
   favoring by the United States Government or the University of California.
   The views and opinions of authors expressed herein do not necessarily
   state or reflect those of the United States Government or the University
   of California, and shall not be used for advertising or product
   endorsement purposes.
******************************************************************************/

